### ISSUE TITLE
Stack choice

### ISSUE THREAD

**Issue by GeorgeHahn** [GeorgeHahn/CS431_Project#1]
Seen here: NodeJS + Express + Sequelize

Would you guys rather work with something like [Iron](http://ironframework.io/), [**Nancy**](http://nancyfx.org/), [Chicago Boss](http://chicagoboss.org/), [Yesod](http://www.yesodweb.com/), or other?

**Comment by adamr5000** [comment]
Woah, sorry for not responding. I can't remember if the professor mentioned any structural requirements, though I don't think he did. With that in mind... well, honestly, I haven't had enough experience with database projects - my two classroom projects were basic MVC setups (as required by the courses) - to really know what to pick here. Feeling sorta out of my depth there...

Do you have any preference in that regard? Whatever one we use, it's gonna be a learning process for me, so if there's one you'd rather use (or one you haven't used and want to learn), I'm all for it.

**Comment by GeorgeHahn** [comment]
If we want to toss something together quickly, Nancy is my preference. It's light enough that we can run with whatever ORM or sans-ORM if necessary. C# is a great language and has amazing tooling and decent OSS library support. The issue here is if either of you run Linux, as you'll have to get Mono up and running (and won't have the amazing Visual Studio tooling & addin ecosystem).

I started learning Haskell over the weekend and can confidently say we shouldn't use it. It's a really cool language, but it's pretty mind-bending coming from more familiar languages.

**Comment by adamr5000** [comment]
I'm not running Linux (at least not as my regular environment), so in that regard it's up to what Sai has. I can brush up on C#, at least enough to get this assignment done (only worked with C++ and C). Shouldn't be too much trouble though.

**Comment by GeorgeHahn** [comment]
To reiterate what was said in class: we can use an ORM. I'm still leaning towards C# with an ORM just so we can get this done quickly and painlessly. Thoughts?

**Comment by adamr5000** [comment]
Funnily enough, I happened to read through that blog post earlier today - spends most of his time railing against Hibernate more than anything, and then only replies to comments agreeing with him. I won't pretend to know what I'm talking about in this arena, but that's never a great sign, hehe.

Anyway, an ORM sounds good to me.

**Comment by GeorgeHahn** [comment]
Some .Net ORMs:
[Some dude complaining about them](http://www.codeguru.com/columns/dotnet/the-sorry-state-of-.net-orms.html)

NuGet packages tagged as [ORM](http://nugetmusthaves.com/Tag/orm) [Micro-ORM](http://nugetmusthaves.com/Tag/micro-orm)

**Comment by somsai002** [comment]
I run windows. I don't really have any experience with this project. Iam decent with C but don't really know C#.

**Comment by somsai002** [comment]
I think ORM sounds good.

**Comment by GeorgeHahn** [comment]
Cool, we should all be able to get up and running pretty quickly with C#. It's definitely not C or C++, but it will feel familiar. Once we get a topic figured out, I'll throw together a little skeleton backend and we can see how we feel about the various ORM options.

**Comment by GeorgeHahn** [comment]
I'm looking pretty strongly at ORMLite + Postgres. ORMLite because it allows us to build tables from code and Postgres just because I prefer it to MySQL. I'll post back after I've had the chance to experiment.

**Comment by GeorgeHahn** [comment]
I've added some basic scaffolding. If you build and run it, you'll be able to store and retrieve objects pretty easily. I switched to Entity Framework 7 because I was having trouble getting ORMLite to store referenced objects. EF7 didn't actually handle this any better (and will give some trouble with Postgres due to Postgres being picky about capitalization). I'm going to try ORMLite and EF7 with MySQL later and see how things work out.

Right now, we can `Database.Store(someobject);` without any trouble - but if `someobject` contains any other objects, they'll get ignored. The behavior I'd like to see is that `someobject.otherobject` gets stored into its own table (`someobject` would store the `otherobject` id in a row). I don't actually know if we'll need that functionality, but it could come in handy.

**Comment by GeorgeHahn** [comment]
Alright, so I switched back to ORMLite and tested it with MySQL. I'm still seeing the same behavior though, so I'm not sure what I'm doing incorrectly.

**Comment by GeorgeHahn** [comment]
Got it! See [this chunk of code](https://github.com/GeorgeHahn/CS431_Project/blob/master/IndexModule.cs#L86,L104) for the syntax.

**Comment by GeorgeHahn** [comment]
Here's a good ServiceStack.OrmLite example: https://github.com/ServiceStack/ServiceStack.OrmLite/blob/master/tests/ServiceStack.OrmLite.Tests/UseCase/CustomerOrdersUseCase.cs

I'm going to close this as our stack is pretty complete now.
