### ISSUE TITLE
Properly handle different promotion types in the UI

### ISSUE THREAD

**Issue by GeorgeHahn** [GeorgeHahn/CS431_Project#13]
From the [frontend code](https://github.com/GeorgeHahn/CS431_Project/blob/1b95441c1d5aa75032f8f4c9e16f75e304f3c7e8/views/NewPromotion.cshtml#L38)

```  TODO: This needs to handle the above dropdown and either hide, show a percent indicator, or show a dollar indicator ```

**Comment by GeorgeHahn** [comment]
@adamr5000 @somsai002 Alternatively, if you want to work with the frontend, it would be really cool if the promotions view automatically switched between % and $ depending on the promotion type. This shouldn't require more than a bit of JS in the `NewPromotion` view.

**Comment by adamr5000** [comment]
Alright, I'm embarrassed, but everything I thought would work hasn't been. How do I fetch the text of whatever's selected in the Promo Type drop down menu? I can get a function to trigger whenever the value there is changed, but nothing I'm trying seems to return the value it's at. The closest I've gotten is by using $(this).text inside the value slider's script, but that always returns the list of all the options no matter what is selected, like this:

Flat rate
Percentage
Free

Again, I'm sorry for this. Looking online wasn't much help either.

**Comment by GeorgeHahn** [comment]
Not 100% sure, but it should be something like [this](http://stackoverflow.com/questions/1085801/get-selected-value-in-dropdown-list-using-javascript)

**Comment by adamr5000** [comment]
Finally! I didn't realize I'd have to get the object separately through the DOM like that answer says to. I mean, I shouldn't need to if I already have a reference to it and am detecting when it changes, right? But if that does the trick I'm not going to complain.

**Comment by adamr5000** [comment]
Made progress:
8f4e1d282ee235a7d7ade5161f7b1926651333ce

Like I said there, though, there are a couple of cosmetic issues remaining. Actually, the integer-value thing might not just be cosmetic.

**Comment by somsai002** [comment]
Can we meet tmmr at 4 pm. 2 hours before class to finalize the presentation
points.

**Comment by GeorgeHahn** [comment]
Last two commits solve the two issues you noted in 8f4e1d2. Pull and close the changes look good.

Great work, the promo page looks awesome!

**Comment by adamr5000** [comment]
I have class at 4. I suppose if really needed I can skip class. I could more likely leave early, so if you two wanted to meet at 4 I could join you some time around 4:45 or 5 or so.

**Comment by somsai002** [comment]
okay, George and I can start working on it and Adam will join us
