### ISSUE TITLE
Project Topic

### ISSUE THREAD

**Issue by GeorgeHahn** [GeorgeHahn/CS431_Project#2]
You guys have any thoughts?

**Comment by somsai002** [comment]
What are the project guidelines

**Comment by GeorgeHahn** [comment]
5-6 tables, not much other guidance given.

**Comment by GeorgeHahn** [comment]
{x} tracker - Users can move ("checkout"/"return") {x}s. If we want one more table, users can remove {x}s ("purchase", "expend", etc).

User table
Location table
{x} table
Users x {x} table
Location x {x} table

x can be anything. Cars, chalk in classrooms, equipment, etc. We could easily make that globally configurable or store the type of thing in the {x} table.

**Comment by GeorgeHahn** [comment]
Building maintenance tracker - Users can submit maintenance requests and log maintenance actions

User table
Maintenance request table
Maintenance action table
Action x request table
Users x request table
Users x action table

**Comment by GeorgeHahn** [comment]
Movies
- Titles
- Ratings
- Duration
- Genre

Customers
 - Name

Showings
- Pricing
- Screen number

Purchases
- Customer ID
- Movie ID
- Purchase time, method, etc
- Purchase type (online, booth)

Last table was?

**Comment by adamr5000** [comment]
As requested, the items I wrote down.

A movies table could include ratings, awards won, 3D/IMAX/other viewing considerations, duration, genre - that sort of thing.

A customers table would have their name, a unique customer ID, and what concessions they're buying. In addition (possibly as its own table), it would have what movies each customer is seeing.

A showtimes table would of course have the movie being shown, the times it is being screened, the screen/theater number (however you want to call it), and the number of seats remaining for that showtime before it's sold out. If we're tying prices to showtimes, then that would go here as well.

A concessions table would list items, prices, and presumably sales figures. Total revenue could be computed from that.

There was also talk of having a table of discounts and current/past promotions. Perhaps the info from here could be automatically applied to the prices in other tables, where appropriate.

**Comment by GeorgeHahn** [comment]
I just did a first pass on the model specs. I'm not 100% sure on them, but they should give us a good start. How do they look? (See [ModelBag.cs](https://github.com/GeorgeHahn/CS431_Project/blob/master/Models/ModelBag.cs))

**Comment by GeorgeHahn** [comment]
I just checked the tables that are created for the current models in Postgres, they're as follows:

```SQL
CREATE TABLE customer
(
  customer_id serial NOT NULL,
  name text,
  CONSTRAINT customer_pkey PRIMARY KEY (customer_id)
)

CREATE TABLE movie
(
  movie_id serial NOT NULL,
  duration integer NOT NULL,
  release_date timestamp without time zone NOT NULL,
  genre text NOT NULL,
  title text,
  CONSTRAINT movie_pkey PRIMARY KEY (movie_id)
)

CREATE TABLE promotion
(
  promotion_id serial NOT NULL,
  promotion_code text,
  expiration timestamp without time zone NOT NULL,
  promo_type text NOT NULL,
  promo_value numeric(38,6) NOT NULL,
  CONSTRAINT promotion_pkey PRIMARY KEY (promotion_id)
)

CREATE TABLE purchase
(
  purchase_id serial NOT NULL,
  movie_id integer NOT NULL,
  showing_id integer NOT NULL,
  customer_id integer NOT NULL,
  promotion_id integer,
  purchase_time timestamp without time zone NOT NULL,
  CONSTRAINT purchase_pkey PRIMARY KEY (purchase_id)
)

CREATE TABLE showing
(
  showing_id serial NOT NULL,
  price numeric(38,6) NOT NULL,
  "time" timestamp without time zone NOT NULL,
  screen_number integer NOT NULL,
  total_seats integer NOT NULL,
  available_seats integer NOT NULL,
  movie_id integer NOT NULL,
  CONSTRAINT showing_pkey PRIMARY KEY (showing_id)
)
```

We can definitely relax those not nulls - that's just a matter of adding some `?`s to fields in [ModelBag.cs](https://github.com/GeorgeHahn/CS431_Project/blob/master/Models/ModelBag.cs)

One observation is that OrmLite has chosen to serialize the enumerations (movie genre and promotion type) as strings rather than integers. This isn't a pressing issue for us, but it means that changing the names of any values in those enumerations would put the database into an inconsistent state. So even though this would probably matter _a lot_ were we a production team, we don't need to care much as we can wipe the db whenever we want. Still, it wouldn't be a bad thing if this behavior were modified such that the enums were serialized as integer values.

**Comment by GeorgeHahn** [comment]
As this issue is pretty general, I'm going to close it. Feel free to comment here or open another issue if you have any thoughts on the comment above.
