### ISSUE TITLE
Add ability to edit objects in database

### ISSUE THREAD

**Issue by adamr5000** [GeorgeHahn/CS431_Project#21]
- [x] Movies
- [x] Showings
- [x] Promotions
- [x] Purchases
- [x] Customers

**Comment by GeorgeHahn** [comment]
This is going to require some view modifications - we should be able to use the `New*` views for editing, but we need to make them populate the inputs with existing data (when it's available).

Ultimately, this will involve something along the lines of: add an `edit` route, have it look up the object then pass its model to the appropriate `New*` view. Finally, modify the `New*` views to support showing data from existing models.

**Comment by GeorgeHahn** [comment]
This is done for movies; I didn't get genre editing to work correctly. TODO.

**Comment by GeorgeHahn** [comment]
As of ae15efa

Frontend is done for showtimes, customers, and promotions. Sort of done for promotions.

Backend is still TODO.

**Comment by GeorgeHahn** [comment]
As of 4add1b2, promotion views are working again

**Comment by GeorgeHahn** [comment]
@adamr5000 @somsai002 If you want to mess with the backend, adding edit/delete to the `Promotions` module would be a pretty good place to get started. You should be able to use the changes from c6183fc as a reference.

**Comment by GeorgeHahn** [comment]
Super easy now that most of the CRUD code is shared.
