### ISSUE TITLE
Clean up the edit/delete buttons

### ISSUE THREAD

**Issue by GeorgeHahn** [GeorgeHahn/CS431_Project#24]
![2015-11-12 09_27_48-start](https://cloud.githubusercontent.com/assets/502747/11120697/aaa7378c-891f-11e5-9e5a-096fe303ca83.png)

**Comment by GeorgeHahn** [comment]
This is rendered by the `EditUI` view. It should be pretty straightforward to fix with some HTML and/or CSS changes.

**Comment by adamr5000** [comment]
Hardcoding it doesn't really seem right, but in this case we want just these two to be exactly the same... doesn't really warrant upending the whole CSS for it. 
Commit 05711a113c1da1fcb611a01f670468e4678138dc

![image](https://cloud.githubusercontent.com/assets/11198351/11198515/3280b6a8-8c93-11e5-9e22-d556cdb53f24.png)
