### ISSUE TITLE
Presentation details

### ISSUE THREAD

**Issue by adamr5000** [GeorgeHahn/CS431_Project#32]
Sai is working on the presentation, or at least that's my understanding of it. I'll have the ER diagram finalized before the weekend is out. The only other major gap I can think of is how we're going to show the state/contents of the database as we go through the presentation, as per the requirements.

That said (unless I missed this already happening), should we sign up to present on November 30th or December 7th? Of course, keep in mind that, knowing the usual state of college assignments, if we want the latter we'd better sign ourselves up  for it ASAP.

**Comment by GeorgeHahn** [comment]
Let's go later - we need the time to get the `Customer` code sorted out. Could you email the prof?

**Comment by adamr5000** [comment]
I'm on it

**Comment by GeorgeHahn** [comment]
For viewing the DB, see [DBeaver](http://dbeaver.jkiss.org/).

**Comment by GeorgeHahn** [comment]
Any response as to which date we got?

**Comment by adamr5000** [comment]
Nothing yet, which is really worrying...

**Comment by somsai002** [comment]
Okay I have the slides layout done. I need the er diagram. I shared the
project with the both of u, its on Google slides.

**Comment by adamr5000** [comment]
I uploaded the most recent ER diagram (v4) to the Git repository yesterday.

**Comment by GeorgeHahn** [comment]
> I uploaded the most recent ER diagram (v4) to the Git repository
yesterday.

Where?

**Comment by adamr5000** [comment]
Yeah, I deleted my comment because it was brought to my attention that... well, that wasn't true. I'm doubly confused - not only was it not in the repository, the PNG wasn't even on my computer anymore, I had to re-generate it. It's in the presentation for now, at least.

**Comment by GeorgeHahn** [comment]
Hmm. There are a few ways that could happen. Perhaps you committed it to a
branch that wasn't pushed to github? If you subsequently changed branches,
the file would disappear like you observed.

**Comment by adamr5000** [comment]
I checked Moodle again - we're confirmed for December 7th. (phew)

**Comment by somsai002** [comment]
Good. I was no where near done with the presentation.

**Comment by adamr5000** [comment]
Alright, I updated the ER diagram again to v5 (and made sure it committed this time... or at least I can see it there). I'm working on those two issues I picked up tonight. Sai, when you get a chance, could you put the updated ER diagram into the presentation? Thanks.

**Comment by adamr5000** [comment]
Never mind, I just put the new ER diagram into the presentation myself. Also it would probably help if we had a... well, "script" isn't the right word, but at least an idea of the order we want to do things when it comes time to show the program. I figure that with so many teams presenting tomorrow we probably won't have the luxury to figure it out on the fly.

**Comment by somsai002** [comment]
So I'm not sure what we need to put for table structure. George this has to
do with the back end stuff. Can u help me with this.

**Comment by GeorgeHahn** [comment]
Sure, what sort of table structure info do we need? Our tables currently look like this, as per DBeaver

![cols](https://cloud.githubusercontent.com/assets/502747/11616523/77cfbe80-9c4b-11e5-8796-5a5cde9bef28.png)

**Comment by GeorgeHahn** [comment]
Googling for table structure shows something more like this, but with lines connecting related models.

![2015-12-06 19_05_09-photos](https://cloud.githubusercontent.com/assets/502747/11616554/602e5e3e-9c4c-11e5-8564-1b22addbe719.png)
