### ISSUE TITLE
Show purchase price on New Purchase page

### ISSUE THREAD

**Issue by GeorgeHahn** [GeorgeHahn/CS431_Project#35]
Should be as simple as:

 - Pull showing price
 - Subtract promotion amount
 - Update UI field

**Comment by GeorgeHahn** [comment]
Partially done - showing price is shown on the purchase list (promo is not accounted for)

**Comment by adamr5000** [comment]
Alright, got it working. I accidentally left in console debugging print statements in the main commit f730c8b2e508c1c8cffc3f21baa02e75cafaac6a, so there's a followup 898bf4225de7a849f9fb1db65000c4c4e997f5ec that just gets rid of those. Here's the output of, in order: no promotion, free promotion, flat-rate promotion, and percentage promotion. 
![image](https://cloud.githubusercontent.com/assets/11198351/11616085/cdd54d2e-9c3f-11e5-8c58-9a7a2c0376a6.png)

Note that, with the way it's coded now, it's a bit ambiguous what "Value" means when you're making a percentage promotion. If I put in 25%, does that mean "25% off," or ""it costs 25% of its normal price, so 75% off"? Right now it's coded as the latter, but it wouldn't be too difficult to change it to the former if desired. Just something to be cognizant about.

**Comment by GeorgeHahn** [comment]
:trophy:
