### ISSUE TITLE
Scheduling

### ISSUE THREAD

**Issue by GeorgeHahn** [GeorgeHahn/CS431_Project#39]
I get out of class at 4pm tomorrow, but I'd like to get food before we present. Can we meet near the bell at 4:15 or so?

**Comment by somsai002** [comment]
Sounds good

**Comment by adamr5000** [comment]
Alright. If/when you guys move from there just let me know either here or by text and I'll meet you there as soon as I can. I forget, are we presenting off one of our computers? That would be ideal, just have to pick a computer and get it set up when we meet.

**Comment by GeorgeHahn** [comment]
I'm not sure, but I'll be bringing a micro-HDMI to HDMI cable and an
external mouse/keyboard.
