### ISSUE TITLE
Topic Refinement

### ISSUE THREAD

**Issue by GeorgeHahn** [GeorgeHahn/CS431_Project#5]
Are we thinking something along the lines of a tool that a cinema's employees would use at the front door/for management (maybe with one or two user-facing pages), or something with more customer facing pages?

For the former, employees can: add/edit new movies, showtimes, promotions; create new purchases.
If we chose to have any customer facing pages, they would be able to do something like: view movie list, showing list, maybe search, and maybe make purchases.

**Comment by adamr5000** [comment]
I was thinking the first one. Then again, maybe it would make more sense to make it just employee-facing?

**Comment by GeorgeHahn** [comment]
I also like the first one better. The less customer facing pages we have, the easier the project will be (smaller scope -> less frontend to write, less backend to hold it up). Since we get to write the requirements :smirk:
